spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
  springdoc:
    defualt-produces-media-type: application/json
  server:
    servlet:
      context-path: /api/v1/