spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bsn101
    username: devuser
    password: devuserlogin123$
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: yuva.web.dev1@gmail.com
    password: ygbeesqsdbafzazg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
server:
  port: 8088
application:
  security:
    jwt:
      secret-key: 1d0f473a137504e7e8d35e26b4146578d66f8f9929b6665992162ef3bb065132
      expiration: 8640000
  file:
    upload:
      photo-output-path:
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
